// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Wnc6eQTbilXeaZx9gahqlc3rVhAzcyY',
    appId: '1:686688409966:web:1299651fd701c92ddd497f',
    messagingSenderId: '686688409966',
    projectId: 'dev-mandu',
    authDomain: 'dev-mandu.firebaseapp.com',
    storageBucket: 'dev-mandu.appspot.com',
    measurementId: 'G-VRKF6BGB3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEX7rUMQIjyxU5UdIuYGUe6Jo4Emyf6q4',
    appId: '1:686688409966:android:0fc42ca807382f0add497f',
    messagingSenderId: '686688409966',
    projectId: 'dev-mandu',
    storageBucket: 'dev-mandu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIbdgDFJKrHtaBMX1vprP9m7MMVjLF-tc',
    appId: '1:686688409966:ios:ad5cb33b02728297dd497f',
    messagingSenderId: '686688409966',
    projectId: 'dev-mandu',
    storageBucket: 'dev-mandu.appspot.com',
    iosClientId: '686688409966-35op6juf3dupp8h85g3pqn90hus4ah2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.devmandu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIbdgDFJKrHtaBMX1vprP9m7MMVjLF-tc',
    appId: '1:686688409966:ios:3d317074eb64ec86dd497f',
    messagingSenderId: '686688409966',
    projectId: 'dev-mandu',
    storageBucket: 'dev-mandu.appspot.com',
    iosClientId: '686688409966-1gavomlaum6152b1e87hrqfd5ld22eh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.devmandu.RunnerTests',
  );
}
